/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AgendaController;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentEvent;
import java.awt.event.ContainerEvent;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author erick
 */
public class Agenda extends javax.swing.JFrame {
    private final AgendaController controller;
    private JTable TableMensalidade;
    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);
        iniciar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        TableMensalidade1 = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabelData = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jTextValor = new javax.swing.JTextField();
        jComboBoxAluno = new javax.swing.JComboBox<>();
        jComboBoxServico = new javax.swing.JComboBox<>();
        TituloAgenda = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jLabelAluno = new javax.swing.JLabel();
        jLabelServico = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        try {
            jLabelFundoAgenda =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "View.Agenda_jLabelFundoAgenda");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableMensalidade1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ALUNO", "SERVIÇO", "VALOR", "DATA", "OBSERVAÇAO"
            }
        ));
        jScrollPane3.setViewportView(TableMensalidade1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 490, 290));

        jToggleButton1.setBackground(new java.awt.Color(51, 255, 51));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(153, 153, 153));
        jToggleButton1.setText("Renovar");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 240, 50));

        jLabelData.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(204, 204, 204));
        jLabelData.setText("Data");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 269, 40, 40));

        jTextId.setText("    ");
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, 30));

        jTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 242, 130, 30));

        getContentPane().add(jComboBoxAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, 30));

        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 130, 30));

        TituloAgenda.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        TituloAgenda.setForeground(new java.awt.Color(204, 204, 204));
        TituloAgenda.setText("Agenda");
        getContentPane().add(TituloAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 150, 50));

        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 130, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Observação:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, 30));

        jLabelId.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelId.setForeground(new java.awt.Color(204, 204, 204));
        jLabelId.setText("ID");
        getContentPane().add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 30, 50));

        jLabelAluno.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelAluno.setForeground(new java.awt.Color(204, 204, 204));
        jLabelAluno.setText("Aluno");
        getContentPane().add(jLabelAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, 40));

        jLabelServico.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(204, 204, 204));
        jLabelServico.setText("Serviço");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 60, 40));

        jLabelValor.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(204, 204, 204));
        jLabelValor.setText("Valor R$");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 240, 120));

        jLabelFundoAgenda.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabelFundoAgendaComponentHidden(evt);
            }
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jLabelFundoAgendaComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabelFundoAgendaComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabelFundoAgendaComponentShown(evt);
            }
        });
        getContentPane().add(jLabelFundoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jTextValorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorActionPerformed

    private void jFormattedTextField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jLabelFundoAgendaComponentMoved(ComponentEvent evt) {//GEN-FIRST:event_jLabelFundoAgendaComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFundoAgendaComponentMoved

    private void jLabelFundoAgendaComponentResized(ComponentEvent evt) {//GEN-FIRST:event_jLabelFundoAgendaComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFundoAgendaComponentResized

    private void jLabelFundoAgendaComponentShown(ComponentEvent evt) {//GEN-FIRST:event_jLabelFundoAgendaComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFundoAgendaComponentShown

    private void jLabelFundoAgendaComponentHidden(ComponentEvent evt) {//GEN-FIRST:event_jLabelFundoAgendaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFundoAgendaComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTable TableMensalidade1;
    private JLabel TituloAgenda;
    JComboBox<String> jComboBoxAluno;
    JComboBox<String> jComboBoxServico;
    private JFormattedTextField jFormattedTextField1;
    private JLabel jLabel1;
    private JLabel jLabelAluno;
    private JLabel jLabelData;
    protected JLabel jLabelFundoAgenda;
    private JLabel jLabelId;
    private JLabel jLabelServico;
    private JLabel jLabelValor;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane3;
    private JTextArea jTextArea1;
    private JTextField jTextId;
    private JTextField jTextValor;
    private JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizaTabela();
    }

    public JTable getTableMensalidade() {
        return TableMensalidade;
    }

    public void setTableMensalidade(JTable TableMensalidade) {
        this.TableMensalidade = TableMensalidade;
    }

    private void initComponents() {
        
    }
    
    
} 
